version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9980:8000"
    volumes:
      - /mnt/sdb3/ETS2LAData:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9980/heartbeat"]
      interval: 5m
      timeout: 3s
