version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9981:8000"
    volumes:
      - /mnt/Zenith/ets2la/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.125:9981/heartbeat"]
      interval: 5m
      timeout: 3s
